### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ProMcTagonist**
laughingToxDevs.png

### CODE REVIEW

**Comment by ProMcTagonist** [comment]
[laughing intensifies]

**Comment by savetheinternet** [comment]
You are laughing over the absence of a comma in the README of software you don't use?

[Seek help.](http://stopnerds.org)

**Comment by ProMcTagonist** [comment]
[Tox devs are roaring heartily and weeping as they clash their mugs joyously and try not to fall over]

**Comment by russelg** [comment]
You are actually autistic.

**Comment by infamousbutterly** [comment]
This thread gave me cancer.

**Comment by ProMcTagonist** [comment]
[Tox devs stifle their continued laughter, attempting to deliver you some final respect as they crowd around your hospital bed. You reach your shaking hand up and motion closer. "I.. Invented... h..."  You fall back gently, and pass away as the cancer takes you.]

**Pull request closed without merging**
