### PR TITLE
citeReply() includes selected text

### PR DESCRIPTION
**Pull request by duanemoody**
IE forking removed, selected text now included

### CODE REVIEW

**Comment by duanemoody** [comment]
Mistake in my code, fixing it before submitting again

**Comment by czaks** [comment]
https://github.com/vichan-devel/vichan/commit/1edaea309b115bbbd17ab121f719cc9bba191c3e

already done

**Comment by kpcyrd** [comment]
So vichan is the new tinyboard? Should we submit pull requests there instead?

**Comment by czaks** [comment]
For the most part, yes.

Tinyboard didn't accept pull requests for a long time now.
7 paź 2014 13:02 "kpcyrd" notifications@github.com napisał(a):

**Pull request closed without merging**
