### PR TITLE
Adds "View Last 50 Posts" pages

### PR DESCRIPTION
**Pull request by MacilPrime**
This makes it so by default, if a thread goes over 100 posts (configurable), a separate page to view the last 50 posts (configurable) is added. I've called this feature in the code and config "noko50" after the feature of some other boards, though "noko50" isn't actually something interpreted in the email field, and the number of posts on the "View Last X Posts" page is configurable.

Every time a post is made to a thread, it's checked whether the thread has over 100 posts or if the noko50 page already exists ("%d+50.html" by default), and if so, it's updated. (This is so if a lot of posts are deleted from a thread bringing it back down below 100 posts, the noko50 page doesn't need to be deleted, and anyone on the noko50 page with a page auto-updating script isn't left in the dust.)

When building the noko50 page, the $thread object used to build the full thread page is re-used. For cases where the noko50 page needs to be generated without the full thread page (like from the mod interface), SQL is done similarly to how thread index previews are made that only gets the most recent 50 posts. The SQL in both of those places probably ought to be consolidated into a single function somewhere due to the similarities.

### CODE REVIEW

**Comment by Circlepuller** [comment]
I personally liked how Kusaba X had that as well, but it had a link on the index pages as well.

**Comment by MacilPrime** [comment]
Yep, this pull req does that too. (The post_thread.html template is not only used to generate the thread pages, but also the thread previews on the index pages.)
This feature (and a few others I haven't gotten around to publishing yet) is live on MLPchan.net and working very well. Recently had a busy thread get over 3600 replies, with many users making use of the view last 50 page, without issues.

However, something important to know when dealing with supermassive threads: if post-hover.js is in use, and someone hovers over a post link to a post that isn't in the current page (say the board index or this view-last-50 page), then post-hover.js will Ajax load the HTML of the full page, including all of its  tags, and as soon as jQuery interprets the HTML string, the browser will start downloading every single reply image thumbnail, often causing the browser to freeze for a few seconds at least. I did a hacky fix (but the only possible simple and good fix as far as I can tell from some quick research) to my post-hover.js, making it apply a regex to the full page's HTML string changing all  tag's src attributes to be renamed to data-src before I have jQuery interpret the HTML string, and later post-hover.js fixes the attribute back only for posts the user wants to view. This entirely prevents the issue where every single thumbnail from the full thread would get loaded. I would cherry-pick the commit fixing post-hover.js for massive threads into this public branch now, but it's a bit intertwined with some of my other changes at the moment.

**Comment by Circlepuller** [comment]
This has my support then. :)

**Comment by savetheinternet** [comment]
I like this, but there should be some way to turn it off (ie. it should be an optional feature). I'm going to fix up a few bugs first and then come back to this. Thanks.

**Pull request closed without merging**
